export class MarketApiError extends Error {
  constructor(public readonly code: string, public readonly status: number) { super(code.replaceAll('_', ' ')); this.name = 'MarketApiError' }
}
async function getJson<T>(path: string): Promise<T> { const response = await fetch(path); if (!response.ok) { const body = await response.json().catch(() => ({})) as { error?: string }; throw new MarketApiError(body.error ?? 'MARKET_REQUEST_FAILED', response.status) } return response.json() as Promise<T> }
function query(path: string, values: Record<string, string | number | undefined>) { const p = new URLSearchParams(); for (const [key, value] of Object.entries(values)) if (value !== undefined && value !== '') p.set(key, String(value)); const suffix = p.toString(); return suffix ? `${path}?${suffix}` : path }

export type MarketEnvelope<T> = { data: T; meta: { source: 'arjum'; fetchedAt: string; dataAsOf: string | null; freshness: 'SNAPSHOT' | 'HISTORICAL' | 'STALE' | 'UNAVAILABLE' } }
export const searchQuery = (q: string) => getJson<MarketEnvelope<Array<{ symbol: string; companyName: string; lastDate: string; normalizedName: string; initials: string }>>>(query('/api/search', { q }))
export const providerScreenerQuery = () => getJson<MarketEnvelope<{ date: string; source: string; cachedForSeconds: number; rows: Array<{ symbol: string; name: string; bucket: string; flags: string; wrEvent: number | string | null; potential: number | string | null; drawdown: number | string | null; note: string }> }>>('/api/screener/latest')
export const analysisQuery = (symbol: string) => getJson<MarketEnvelope<{ symbol: string; document: string }>>(`/api/analysis/${encodeURIComponent(symbol)}`)
export type BrokerRow = { code: string; name: string; buyValue: number; sellValue: number; netValue: number; buyVolume: number; sellVolume: number; netVolume: number; buyFrequency: number; sellFrequency: number; netFrequency: number }
export const brokerSummaryQuery = (symbol: string) => getJson<MarketEnvelope<{ symbol: string; startDate: string; endDate: string; brokers: BrokerRow[]; levels: unknown[] }>>(`/api/broker-summary/${encodeURIComponent(symbol)}`)
export type BrokerAccumulation = { symbol: string; startDate: string; endDate: string; series: Array<{ code: string; name: string; points: Array<{ date: string; netValue: number; netVolume: number; cumulativeNetValue: number; buyAverage: number | null; sellAverage: number | null }> }>; topBuyers: Array<{ code: string; name: string; totalNetValue: number }>; topSellers: Array<{ code: string; name: string; totalNetValue: number }> }
export const brokerAccumulationQuery = (symbol: string, options: { startDate?: string; endDate?: string; top?: number; brokers?: string }) => getJson<MarketEnvelope<BrokerAccumulation>>(query(`/api/broker-accumulation/${encodeURIComponent(symbol)}`, { start_date: options.startDate, end_date: options.endDate, top: options.top, brokers: options.brokers }))
export type HistoryRow = { time: string; open: number; high: number; low: number; close: number; average: number; change: number; changePercent: number; value: number; volume: number; frequency: number; foreignBuy: number; foreignSell: number; foreignNet: number }
export const HISTORY_DEFAULTS = { frame: 'daily', limit: 120 } as const
export const historyQueryKey = (symbol: string, frame: string, limit: number) => ['arjum', 'history', symbol.toUpperCase(), frame, limit] as const
export const historyQuery = (symbol: string, frame: string, limit: number) => getJson<MarketEnvelope<{ symbol: string; frame: string; rows: HistoryRow[] }>>(query(`/api/history/${encodeURIComponent(symbol)}`, { frame, limit }))
export type Seasonality = { symbol: string; months: string[]; rows: Array<{ year: string; average: number | null; values: Array<number | null> }>; summary: Array<{ month: string; average: number | null; upProbability: number | null; samples: number }> }
export const seasonalityQuery = (symbol: string) => getJson<MarketEnvelope<Seasonality>>(`/api/seasonal/${encodeURIComponent(symbol)}`)
export type MarketCap = { date: string; total: number; page: number; perPage: number; totalPages: number; rows: Array<{ symbol: string; name: string; close: number; marketCap: number; listedShares: number; turnover: number }> }
export const marketCapQuery = (date: string, page: number, perPage: number) => getJson<MarketEnvelope<MarketCap>>(query('/api/market-cap', { date, page, per_page: perPage }))
export type Financials = { symbol: string; reportType: string; period: string; count: number; periods: Array<{ year: string; quarter: string; label: string; fetchedAt: string }>; rows: Array<{ key: string; label: string; depth: number; expandable: boolean; values: Array<number | null> }> }
export const financialsQuery = (symbol: string, reportType: string, period: string, year?: string) => getJson<MarketEnvelope<Financials>>(query(`/api/financial-statements/${encodeURIComponent(symbol)}`, { report_type: reportType, period, year, limit: 12 }))
export type Insiders = { symbol: string; count: number; total: number; page: number; pageSize: number; totalPages: number; rows: Array<{ person: string; date: string; action: string; nationality: string; previousHolding: string; currentHolding: string; sharesChange: string; price: string; broker: string; roles: string[] }> }
export const insidersQuery = (symbol: string, page: number, limit: number, actionType?: string) => getJson<MarketEnvelope<Insiders>>(query(`/api/insiders/${encodeURIComponent(symbol)}`, { page, limit, action_type: actionType }))
export type DoneDetails = { symbol: string; date: string; total: number; page: number; perPage: number; totalPages: number; rows: Array<{ time: string; board: string; price: number; lots: number; value: number; buyer: string; seller: string; buyerType: string; sellerType: string; aggressor: string }> }
export const doneDetailsQuery = (symbol: string, date: string, page: number, perPage: number) => getJson<MarketEnvelope<DoneDetails>>(query('/api/done-details', { code: symbol, date, page, per_page: perPage }))
export const providerHealthQuery = () => getJson<MarketEnvelope<{ ok: boolean; status: string }>>('/api/provider-health')
