'use client'
import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { createChart, LineSeries, type Time } from 'lightweight-charts'
import { PriceChart } from '@/components/charts/price-chart'
import { PanelMessage, PanelStatus } from './panel-status'
import { formatCompact, formatNumber, marketDirection } from '@/lib/format'
import {
  analysisQuery, brokerAccumulationQuery, brokerSummaryQuery, doneDetailsQuery, financialsQuery,
  historyQuery, historyQueryKey, HISTORY_DEFAULTS, insidersQuery, marketCapQuery, providerScreenerQuery, searchQuery, seasonalityQuery,
  type BrokerAccumulation, type BrokerRow, type Financials, type HistoryRow, type MarketApiError,
} from '@/lib/api/market-client'
import { createClient } from '@/lib/supabase/client'
import type { RunningTrade, RunningTradeState } from '@/lib/market/arjum/contracts'

function Failure({ error, retry }: { error: Error; retry: () => void }) {
  const code = (error as MarketApiError).code
  const detail = code === 'RATE_LIMITED' ? 'Provider rate limit reached.' : code === 'PROVIDER_UNAUTHORIZED' ? 'Provider credential was rejected.' : code === 'PROVIDER_UNAVAILABLE' ? 'Provider is unavailable.' : error.message
  return <PanelMessage state="ERROR" detail={detail} retry={retry} />
}
function Controls({ choices, value, onChange }: { choices: string[]; value: string; onChange: (value: string) => void }) { return <div className="flex gap-0.5">{choices.map((choice) => <button key={choice} className="terminal-action" data-active={value === choice} onClick={() => onChange(choice)}>{choice}</button>)}</div> }
function Footer({ meta }: { meta: Parameters<typeof PanelStatus>[0]['meta'] }) { return <div className="border-t border-[var(--color-iron)] px-2 py-1 text-[10px]"><PanelStatus meta={meta} /></div> }

export function ProviderChartPanel({ symbol }: { symbol: string }) {
  const [frame, setFrame] = useState<string>(HISTORY_DEFAULTS.frame); const [limit, setLimit] = useState<number>(HISTORY_DEFAULTS.limit)
  const query = useQuery({ queryKey: historyQueryKey(symbol, frame, limit), queryFn: () => historyQuery(symbol, frame, limit) })
  if (query.isPending) return <PanelMessage state="LOADING" detail={`Loading ${symbol} history`} />
  if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />
  if (!query.data.data.rows.length) return <PanelMessage state="EMPTY" detail="No historical bars returned." />
  const rows = query.data.data.rows
  const latest = rows.find((row) => Number.isFinite(row.close))!
  const candles = rows.map((row) => ({ ...row, volume: row.volume, value: row.value, frequency: row.frequency, foreignBuy: row.foreignBuy, foreignSell: row.foreignSell }))
  return <div className="flex h-full flex-col"><div className="flex flex-wrap items-center gap-2 border-b border-[var(--color-iron)] p-1"><Controls choices={['daily', 'weekly', 'monthly']} value={frame} onChange={setFrame} />{[60, 120, 240, 500].map((n) => <button key={n} className="terminal-action" data-active={limit === n} onClick={() => setLimit(n)}>{n}</button>)}<span className="text-[10px] text-[var(--color-ash)]">MA5 · MA20 · MA50 · MACD</span><span className="ml-auto text-[10px] tabular-nums">O {formatNumber(latest.open)} H {formatNumber(latest.high)} L {formatNumber(latest.low)} C {formatNumber(latest.close)} VOL {formatCompact(latest.volume)}</span></div><div className="min-h-0 flex-1"><PriceChart candles={candles} overlays={['MA5', 'MA20', 'MA50']} macd /></div><Footer meta={query.data.meta} /></div>
}

function providerPercent(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? '—' : `${value > 0 ? '+' : ''}${value.toFixed(2)}%` }
function latestValid(rows: HistoryRow[]) { return rows.find((row) => [row.close, row.open, row.high, row.low].every(Number.isFinite)) ?? null }

export function QuotePanel({ symbol }: { symbol: string }) {
  const history = useQuery({ queryKey: historyQueryKey(symbol, HISTORY_DEFAULTS.frame, HISTORY_DEFAULTS.limit), queryFn: () => historyQuery(symbol, HISTORY_DEFAULTS.frame, HISTORY_DEFAULTS.limit) })
  const security = useQuery({ queryKey: ['arjum', 'search', symbol], queryFn: () => searchQuery(symbol), staleTime: 60_000 })
  if (history.isPending) return <PanelMessage state="LOADING" detail={`Loading ${symbol} snapshot`} />
  if (history.isError) return <Failure error={history.error} retry={() => history.refetch()} />
  const row = latestValid(history.data.data.rows)
  if (!row) return <PanelMessage state="EMPTY" detail="No valid historical quote is available." />
  const company = security.data?.data.find((item) => item.symbol === symbol)?.companyName
  return <div className="flex h-full flex-col"><div className="flex items-baseline gap-3 border-b border-[var(--color-iron)] px-2 py-1"><strong className="text-sm cyan">{symbol}</strong><span className="min-w-0 truncate text-[11px] text-[var(--color-fog)]">{company ?? '—'}</span><span className="ml-auto text-[10px] text-[var(--color-ash)]">LATEST {row.time}</span></div><div className="grid flex-1 grid-cols-2 content-start gap-x-4 gap-y-2 p-2 text-[10px] md:grid-cols-3"><QuoteStat label="LAST" value={`${formatNumber(row.close)}  ${providerPercent(row.changePercent)}`} direction={row.change} /><QuoteStat label="O / H / L" value={`${formatNumber(row.open)} / ${formatNumber(row.high)} / ${formatNumber(row.low)}`} /><QuoteStat label="AVG" value={formatNumber(row.average)} /><QuoteStat label="VALUE" value={formatCompact(row.value)} /><QuoteStat label="VOLUME" value={formatCompact(row.volume)} /><QuoteStat label="FREQUENCY" value={formatNumber(row.frequency, 0)} /><QuoteStat label="FOREIGN BUY" value={formatCompact(row.foreignBuy)} /><QuoteStat label="FOREIGN SELL" value={formatCompact(row.foreignSell)} /><QuoteStat label="NET FOREIGN" value={formatCompact(row.foreignNet)} direction={row.foreignNet} /></div><Footer meta={history.data.meta} /></div>
}

function QuoteStat({ label, value, direction }: { label: string; value: string; direction?: number }) { return <div className="min-w-0"><div className="text-[var(--color-steel)]">{label}</div><div className={`truncate text-[12px] tabular-nums ${direction === undefined ? '' : marketDirection(direction)}`}>{value}</div></div> }

export function HistoryPanel({ symbol }: { symbol: string }) {
  const [frame, setFrame] = useState<string>(HISTORY_DEFAULTS.frame); const [limit, setLimit] = useState<number>(HISTORY_DEFAULTS.limit)
  const query = useQuery({ queryKey: historyQueryKey(symbol, frame, limit), queryFn: () => historyQuery(symbol, frame, limit) })
  if (query.isPending) return <PanelMessage state="LOADING" />
  if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />
  return <div className="flex h-full flex-col"><div className="flex gap-1 border-b border-[var(--color-iron)] p-1"><Controls choices={['daily', 'weekly', 'monthly']} value={frame} onChange={setFrame} />{[60, 120, 240].map((value) => <button key={value} className="terminal-action" data-active={limit === value} onClick={() => setLimit(value)}>{value}</button>)}</div><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>DATE</th><th className="numeric">CLOSE</th><th className="numeric">CHANGE</th><th className="numeric">VALUE</th><th className="numeric">VOLUME</th><th className="numeric">FREQ</th><th className="numeric">F BUY</th><th className="numeric">F SELL</th><th className="numeric">NET FOREIGN</th><th className="numeric">OPEN</th><th className="numeric">HIGH</th><th className="numeric">LOW</th><th className="numeric">AVG</th></tr></thead><tbody>{query.data.data.rows.map((row) => <tr key={row.time}><td>{row.time}</td><td className="numeric">{formatNumber(row.close)}</td><td className={`numeric ${marketDirection(row.change)}`}>{formatNumber(row.change)} · {providerPercent(row.changePercent)}</td><td className="numeric">{formatCompact(row.value)}</td><td className="numeric">{formatCompact(row.volume)}</td><td className="numeric">{formatNumber(row.frequency, 0)}</td><td className="numeric">{formatCompact(row.foreignBuy)}</td><td className="numeric">{formatCompact(row.foreignSell)}</td><td className={`numeric ${marketDirection(row.foreignNet)}`}>{formatCompact(row.foreignNet)}</td><td className="numeric">{formatNumber(row.open)}</td><td className="numeric">{formatNumber(row.high)}</td><td className="numeric">{formatNumber(row.low)}</td><td className="numeric">{formatNumber(row.average)}</td></tr>)}</tbody></table></div><Footer meta={query.data.meta} /></div>
}

export function BrokerPanel({ symbol, onFocusBroker }: { symbol: string; onFocusBroker?: (code: string) => void }) {
  const [mode, setMode] = useState('VALUE'); const query = useQuery({ queryKey: ['arjum', 'broker-summary', symbol], queryFn: () => brokerSummaryQuery(symbol) })
  if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />
  const rows = [...query.data.data.brokers].sort((a, b) => mode === 'VOLUME' ? b.netVolume - a.netVolume : mode === 'FREQUENCY' ? b.netFrequency - a.netFrequency : b.netValue - a.netValue)
  if (!rows.length) return <PanelMessage state="EMPTY" />
  return <div className="flex h-full flex-col"><div className="border-b border-[var(--color-iron)] p-1"><Controls choices={['VALUE', 'VOLUME', 'FREQUENCY']} value={mode} onChange={setMode} /></div><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>BROKER</th><th className="numeric">BUY VALUE</th><th className="numeric">SELL VALUE</th><th className="numeric">NET VALUE</th><th className="numeric">BUY VOL</th><th className="numeric">SELL VOL</th><th className="numeric">NET VOL</th><th className="numeric">BUY FREQ</th><th className="numeric">SELL FREQ</th></tr></thead><tbody>{rows.map((row: BrokerRow) => <tr key={row.code} className="cursor-pointer" onClick={() => onFocusBroker?.(row.code)}><td title={row.name} className="cyan">{row.code}</td><td className="numeric">{formatCompact(row.buyValue)}</td><td className="numeric">{formatCompact(row.sellValue)}</td><td className={`numeric ${marketDirection(row.netValue)}`}>{formatCompact(row.netValue)}</td><td className="numeric">{formatCompact(row.buyVolume)}</td><td className="numeric">{formatCompact(row.sellVolume)}</td><td className={`numeric ${marketDirection(row.netVolume)}`}>{formatCompact(row.netVolume)}</td><td className="numeric">{formatNumber(row.buyFrequency, 0)}</td><td className="numeric">{formatNumber(row.sellFrequency, 0)}</td></tr>)}</tbody></table></div><Footer meta={query.data.meta} /></div>
}

const LINE_COLORS = ['#da5c2c', '#8bbdcc', '#7eb89b', '#d08179', '#b4b4b4', '#b99ad4', '#d8c47a', '#79b7ad']
function BrokerLines({ data }: { data: BrokerAccumulation }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const chart = createChart(ref.current, { autoSize: true, layout: { background: { color: '#111111' }, textColor: '#7e7e7e', fontFamily: 'monospace', fontSize: 10 }, grid: { vertLines: { color: '#202020' }, horzLines: { color: '#202020' } } }); data.series.forEach((broker, index) => chart.addSeries(LineSeries, { title: broker.code, color: LINE_COLORS[index % LINE_COLORS.length], lineWidth: 2 }).setData(broker.points.map((point) => ({ time: point.date as Time, value: point.cumulativeNetValue })))); chart.timeScale().fitContent(); return () => chart.remove() }, [data]); return <div ref={ref} role="img" aria-label="Broker cumulative net value chart" className="h-full min-h-48" /> }
export function BrokerAccumulationPanel({ symbol }: { symbol: string }) { const [startDate, setStart] = useState(''); const [endDate, setEnd] = useState(''); const [top, setTop] = useState(5); const [brokers, setBrokers] = useState(''); const query = useQuery({ queryKey: ['arjum', 'broker-accumulation', symbol, startDate, endDate, top, brokers], queryFn: () => brokerAccumulationQuery(symbol, { startDate: startDate || undefined, endDate: endDate || undefined, top, brokers: brokers || undefined }) }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; const data = query.data.data; return <div className="flex h-full flex-col"><div className="flex flex-wrap gap-1 border-b border-[var(--color-iron)] p-1"><input aria-label="Start date" type="date" className="terminal-input" value={startDate} onChange={(e) => setStart(e.target.value)} /><input aria-label="End date" type="date" className="terminal-input" value={endDate} onChange={(e) => setEnd(e.target.value)} /><input aria-label="Top brokers" type="number" min="1" max="20" className="terminal-input w-16" value={top} onChange={(e) => setTop(Number(e.target.value))} /><input aria-label="Specific brokers" className="terminal-input w-36" placeholder="AK,CC,YU" value={brokers} onChange={(e) => setBrokers(e.target.value.toUpperCase())} /></div><div className="grid min-h-0 flex-1 grid-cols-[1fr_150px]"><BrokerLines data={data} /><div className="overflow-auto border-l border-[var(--color-iron)] text-[10px]"><FlowList title="TOP BUYERS" rows={data.topBuyers} /><FlowList title="TOP SELLERS" rows={data.topSellers} /></div></div><Footer meta={query.data.meta} /></div> }
function FlowList({ title, rows }: { title: string; rows: BrokerAccumulation['topBuyers'] }) { return <div><div className="border-b border-[var(--color-iron)] p-1 text-[var(--color-ash)]">{title}</div>{rows.slice(0, 8).map((row) => <div key={row.code} className="flex justify-between border-b border-[var(--color-iron)] px-1 py-0.5"><span>{row.code}</span><span className={marketDirection(row.totalNetValue)}>{formatCompact(row.totalNetValue)}</span></div>)}</div> }

export function SeasonalityPanel({ symbol }: { symbol: string }) { const query = useQuery({ queryKey: ['arjum', 'seasonality', symbol], queryFn: () => seasonalityQuery(symbol) }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; const data = query.data.data; return <div className="flex h-full flex-col"><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>MONTH</th>{data.rows.map((row) => <th className="numeric" key={row.year}>{row.year}</th>)}<th className="numeric">AVG</th><th className="numeric">UP %</th><th className="numeric">N</th></tr></thead><tbody>{data.months.map((month, monthIndex) => { const summary = data.summary.find((row) => row.month === month); return <tr key={month}><td>{month}</td>{data.rows.map((row) => { const value = row.values[monthIndex]; return <td key={row.year} className={`numeric ${marketDirection(value)}`} style={{ backgroundColor: value == null ? undefined : value > 0 ? 'rgba(126,184,155,.12)' : value < 0 ? 'rgba(208,129,121,.12)' : undefined }}>{value == null ? '—' : `${value.toFixed(2)}%`}</td> })}<td className={`numeric ${marketDirection(summary?.average)}`}>{summary?.average == null ? '—' : `${summary.average.toFixed(2)}%`}</td><td className="numeric">{summary?.upProbability == null ? '—' : `${summary.upProbability.toFixed(1)}%`}</td><td className="numeric muted">{summary?.samples ?? '—'}</td></tr>})}<tr><td>YEAR AVG</td>{data.rows.map((row) => <td key={row.year} className={`numeric ${marketDirection(row.average)}`}>{row.average == null ? '—' : `${row.average.toFixed(2)}%`}</td>)}<td colSpan={3}>—</td></tr></tbody></table></div><Footer meta={query.data.meta} /></div> }

export function MarketCapPanel({ onSelect }: { onSelect: (symbol: string) => void }) { const [date, setDate] = useState(''); const [page, setPage] = useState(1); const [perPage, setPerPage] = useState(25); const query = useQuery({ queryKey: ['arjum', 'market-cap', date, page, perPage], queryFn: () => marketCapQuery(date, page, perPage) }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; const d = query.data.data; return <div className="flex h-full flex-col"><div className="flex gap-1 border-b border-[var(--color-iron)] p-1"><input aria-label="Market cap date" type="date" className="terminal-input" value={date} onChange={(e) => { setDate(e.target.value); setPage(1) }} /><select aria-label="Rows per page" className="terminal-input" value={perPage} onChange={(e) => setPerPage(Number(e.target.value))}><option>25</option><option>50</option><option>100</option></select><button className="terminal-action" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>←</button><span className="px-1 py-1 text-[10px]">{page}/{d.totalPages}</span><button className="terminal-action" disabled={page >= d.totalPages} onClick={() => setPage((p) => p + 1)}>→</button></div><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>SYMBOL</th><th>NAME</th><th className="numeric">CLOSE</th><th className="numeric">MARKET CAP</th><th className="numeric">LISTED SHARES</th><th className="numeric">TURNOVER</th></tr></thead><tbody>{d.rows.map((row) => <tr key={row.symbol} className="cursor-pointer" onClick={() => onSelect(row.symbol)}><td className="cyan">{row.symbol}</td><td>{row.name}</td><td className="numeric">{formatNumber(row.close)}</td><td className="numeric">{formatCompact(row.marketCap)}</td><td className="numeric">{formatCompact(row.listedShares)}</td><td className="numeric">{(row.turnover * 100).toFixed(3)}%</td></tr>)}</tbody></table></div><Footer meta={query.data.meta} /></div> }

export function FinancialPanel({ symbol }: { symbol: string }) { const [report, setReport] = useState('INCOME_STATEMENT'); const [period, setPeriod] = useState('quarterly'); const [year, setYear] = useState(''); const [collapsed, setCollapsed] = useState<Set<string>>(() => new Set()); const query = useQuery({ queryKey: ['arjum', 'financials', symbol, report, period, year], queryFn: () => financialsQuery(symbol, report, period, year || undefined) }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; const d: Financials = query.data.data; const visible = d.rows.filter((row) => ![...collapsed].some((key) => row.key.startsWith(`${key}.`))); return <div className="flex h-full flex-col"><div className="flex flex-wrap gap-1 border-b border-[var(--color-iron)] p-1"><Controls choices={['INCOME_STATEMENT', 'BALANCE_SHEET', 'CASH_FLOW']} value={report} onChange={setReport} /><Controls choices={['quarterly', 'annual']} value={period} onChange={setPeriod} /><input aria-label="Financial year" className="terminal-input w-16" placeholder="YEAR" value={year} onChange={(e) => setYear(e.target.value)} /></div><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th className="sticky left-0 z-20 bg-[var(--color-carbon)]">METRIC</th>{d.periods.map((p) => <th className="numeric" key={`${p.year}-${p.quarter}`}>{p.label}</th>)}</tr></thead><tbody>{visible.map((row) => <tr key={row.key}><td className="sticky left-0 z-10 bg-[var(--color-carbon)]" style={{ paddingLeft: `${8 + row.depth * 14}px` }}><button className="text-left" disabled={!row.expandable} onClick={() => setCollapsed((old) => { const next = new Set(old); if (next.has(row.key)) next.delete(row.key); else next.add(row.key); return next })}>{row.expandable ? collapsed.has(row.key) ? '▸ ' : '▾ ' : ''}{row.label}</button></td>{row.values.map((value, i) => <td key={i} className={`numeric ${marketDirection(value)}`}>{formatCompact(value)}</td>)}</tr>)}</tbody></table></div><Footer meta={query.data.meta} /></div> }

export function InsiderPanel({ symbol }: { symbol: string }) { const [page, setPage] = useState(1); const [action, setAction] = useState(''); const query = useQuery({ queryKey: ['arjum', 'insiders', symbol, page, 10, action], queryFn: () => insidersQuery(symbol, page, 10, action || undefined) }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; const d = query.data.data; return <div className="flex h-full flex-col"><div className="flex gap-1 border-b border-[var(--color-iron)] p-1"><Controls choices={['ALL', 'BUY', 'SELL', 'CROSS']} value={action || 'ALL'} onChange={(v) => { setAction(v === 'ALL' ? '' : v.toLowerCase()); setPage(1) }} /><button className="terminal-action ml-auto" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>←</button><span className="px-1 py-1 text-[10px]">{page}/{d.totalPages}</span><button className="terminal-action" disabled={page >= d.totalPages} onClick={() => setPage((p) => p + 1)}>→</button></div><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>DATE</th><th>PERSON</th><th>ROLE</th><th>ACTION</th><th className="numeric">SHARES CHANGE</th><th className="numeric">PREVIOUS HOLDING</th><th className="numeric">CURRENT HOLDING</th><th className="numeric">PRICE</th><th>NATIONALITY</th><th>BROKER</th></tr></thead><tbody>{d.rows.map((row, i) => <tr key={`${row.person}-${row.date}-${i}`}><td>{row.date}</td><td>{row.person}</td><td>{row.roles.join(', ')}</td><td className={row.action === 'BUY' ? 'positive' : row.action === 'SELL' ? 'negative' : 'neutral'}>{row.action}</td><td className="numeric">{row.sharesChange}</td><td className="numeric">{row.previousHolding}</td><td className="numeric">{row.currentHolding}</td><td className="numeric">{row.price}</td><td>{row.nationality}</td><td>{row.broker || '—'}</td></tr>)}</tbody></table></div><Footer meta={query.data.meta} /></div> }

type TopActive = { symbol: string; value: number; tradeCount: number }
function useRunningTrade() {
  const [state, setState] = useState<RunningTradeState>('OFFLINE'); const [marketStatus, setMarketStatus] = useState<string | null>(null); const [sessionStatus, setSessionStatus] = useState<string | null>(null); const [trades, setTrades] = useState<RunningTrade[]>([]); const [top5, setTop5] = useState<TopActive[]>([])
  useEffect(() => { const url = process.env.NEXT_PUBLIC_HEULATRADE_RUNNING_TRADE_GATEWAY_URL; if (!url) return; let socket: WebSocket | null = null; let cancelled = false; void (async () => { try { const { data } = await createClient().auth.getSession(); if (cancelled || !data.session) return; setState('RECONNECTING'); socket = new WebSocket(url); socket.onopen = () => socket?.send(JSON.stringify({ type: 'authenticate', accessToken: data.session!.access_token })); socket.onmessage = (event) => { const value = JSON.parse(String(event.data)) as { type: string; state?: RunningTradeState; marketStatus?: string; sessionStatus?: string; trade?: RunningTrade; trades?: RunningTrade[]; rows?: TopActive[] }; if (value.type === 'connection' && value.state) setState(value.state); if (value.type === 'snapshot') { const market = value.marketStatus?.toUpperCase() ?? ''; setState(market.includes('BREAK') ? 'MARKET BREAK' : market.includes('CLOSED') ? 'MARKET CLOSED' : 'LIVE'); setMarketStatus(value.marketStatus ?? null); setSessionStatus(value.sessionStatus ?? null); setTrades((value.trades ?? []).slice(-500).reverse()) } if (value.type === 'trade' && value.trade) setTrades((old) => [value.trade!, ...old].slice(0, 500)); if (value.type === 'top5') setTop5(value.rows ?? []) }; socket.onclose = () => { if (!cancelled) setState('OFFLINE') }; socket.onerror = () => setState('OFFLINE') } catch { setState('OFFLINE') } })(); return () => { cancelled = true; socket?.close() } }, [])
  return { state, marketStatus, sessionStatus, trades, top5 }
}
function LiveTape({ symbol }: { symbol?: string }) { const live = useRunningTrade(); const trades = symbol ? live.trades.filter((row) => row.symbol === symbol) : live.trades; if (live.state === 'OFFLINE' && !trades.length) return <PanelMessage state="UNAVAILABLE" detail="Running-trade gateway is offline or not configured." />; return <div className="grid h-full min-h-0 grid-cols-[1fr_170px]"><div className="min-h-0 overflow-auto"><div className="flex gap-3 border-b border-[var(--color-iron)] px-2 py-1 text-[10px]"><span>{live.state}</span><span>MARKET {live.marketStatus ?? '—'}</span><span>SESSION {live.sessionStatus ?? '—'}</span></div><table className="mono-table"><thead><tr><th>TIME</th><th>SYMBOL</th><th>ACTION</th><th className="numeric">PRICE</th><th className="numeric">LOT</th><th className="numeric">VALUE</th><th className="numeric">CHANGE</th></tr></thead><tbody>{trades.map((row) => <tr key={`${row.tradeNumber}-${row.symbol}`}><td>{row.time}</td><td className="cyan">{row.symbol}</td><td className={row.action === 'BUY' ? 'positive' : 'negative'}>{row.action}</td><td className="numeric">{formatNumber(row.price)}</td><td className="numeric">{formatNumber(row.lots)}</td><td className="numeric">{formatCompact(row.value)}</td><td className={`numeric ${marketDirection(row.priceChange)}`}>{formatNumber(row.priceChange)}</td></tr>)}</tbody></table></div><div className="overflow-auto border-l border-[var(--color-iron)]"><div className="border-b border-[var(--color-iron)] p-1 text-[10px] text-[var(--color-ash)]">TOP 5 ACTIVE</div>{live.top5.map((row) => <div key={row.symbol} className="flex justify-between border-b border-[var(--color-iron)] p-1 text-[10px]"><span className="cyan">{row.symbol}</span><span>{formatCompact(row.value)}</span></div>)}</div></div> }
export function TapePanel({ symbol }: { symbol: string }) { const [tab, setTab] = useState('HISTORY'); const [date, setDate] = useState(''); const [page, setPage] = useState(1); const query = useQuery({ queryKey: ['arjum', 'done-details', symbol, date, page, 100], queryFn: () => doneDetailsQuery(symbol, date, page, 100), enabled: tab === 'HISTORY' }); return <div className="flex h-full flex-col"><div className="flex gap-1 border-b border-[var(--color-iron)] p-1"><Controls choices={['LIVE', 'HISTORY']} value={tab} onChange={setTab} />{tab === 'HISTORY' && <><input aria-label="Tape date" type="date" className="terminal-input" value={date} onChange={(e) => { setDate(e.target.value); setPage(1) }} /><span className="px-1 py-1 text-[10px]">{query.data ? `${page}/${query.data.data.totalPages} · ${formatNumber(query.data.data.total, 0)}` : '—'}</span><button className="terminal-action ml-auto" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>←</button><button className="terminal-action" disabled={Boolean(query.data && page >= query.data.data.totalPages)} onClick={() => setPage((p) => p + 1)}>→</button></>}</div>{tab === 'LIVE' ? <div className="min-h-0 flex-1"><LiveTape symbol={symbol} /></div> : query.isPending ? <PanelMessage state="LOADING" /> : query.isError ? <Failure error={query.error} retry={() => query.refetch()} /> : !query.data.data.rows.length ? <PanelMessage state="EMPTY" /> : <><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>TIME</th><th>ACTION</th><th className="numeric">PRICE</th><th className="numeric">LOT</th><th className="numeric">VALUE</th><th>BUYER</th><th>SELLER</th><th>BUYER TYPE</th><th>SELLER TYPE</th><th>BOARD</th></tr></thead><tbody>{query.data.data.rows.map((row, i) => <tr key={`${row.time}-${i}`}><td>{row.time}</td><td className={row.aggressor === 'BUY' ? 'positive' : row.aggressor === 'SELL' ? 'negative' : 'neutral'}>{row.aggressor}</td><td className="numeric">{formatNumber(row.price)}</td><td className="numeric">{formatNumber(row.lots)}</td><td className="numeric">{formatCompact(row.value)}</td><td>{row.buyer}</td><td>{row.seller}</td><td>{row.buyerType}</td><td>{row.sellerType}</td><td>{row.board}</td></tr>)}</tbody></table></div><Footer meta={query.data.meta} /></>}</div> }

export function AnalysisPanel({ symbol }: { symbol: string }) { const query = useQuery({ queryKey: ['arjum', 'analysis', symbol], queryFn: () => analysisQuery(symbol) }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; return <div className="flex h-full flex-col"><div className="border-b border-[var(--color-iron)] px-2 py-1 text-[10px] text-[var(--color-ash)]">PROVIDER-GENERATED ANALYSIS · NOT RAW MARKET FACT</div><pre className="terminal-scroll min-h-0 flex-1 overflow-auto whitespace-pre-wrap p-3 font-mono text-[11px] leading-5">{query.data.data.document}</pre><Footer meta={query.data.meta} /></div> }

export function ProviderScreenerPanel({ onSelect }: { onSelect: (symbol: string) => void }) { const query = useQuery({ queryKey: ['arjum', 'screener', 'latest'], queryFn: providerScreenerQuery }); if (query.isPending) return <PanelMessage state="LOADING" />; if (query.isError) return <Failure error={query.error} retry={() => query.refetch()} />; return <div className="flex h-full flex-col"><div className="min-h-0 flex-1 overflow-auto"><table className="mono-table"><thead><tr><th>SYMBOL</th><th>NAME</th><th>BUCKET</th><th>FLAGS</th><th>WR EVENT</th><th>POTENTIAL</th><th>DRAWDOWN</th><th>NOTE</th></tr></thead><tbody>{query.data.data.rows.map((row) => <tr key={row.symbol} className="cursor-pointer" onClick={() => onSelect(row.symbol)}><td className="cyan">{row.symbol}</td><td>{row.name}</td><td>{row.bucket}</td><td>{row.flags}</td><td>{row.wrEvent ?? '—'}</td><td>{row.potential ?? '—'}</td><td>{row.drawdown ?? '—'}</td><td>{row.note}</td></tr>)}</tbody></table></div><Footer meta={query.data.meta} /></div> }

export function LivePanel() { return <LiveTape /> }
